### ISSUE TITLE
Impossible to logout

### ISSUE THREAD

**Issue by zgorizzo69** [threefoldtech/0-hub#14]
step to reproduce 
* try to go to docker converter https://hub.grid.tf/docker-convert#
* login
* logout
* go to docker converter again
* still logged in

**Comment by maxux** [comment]
Actually, you're logged out, but when you try to reach a protected page, you're redirected to itsyou.online login and you're automatically re-logged in. I'm checking how to fix this.

**Comment by maxux** [comment]
This is only true for itsyou.online authentication which will be dropped anytime soon, already deprecated.
