### ISSUE TITLE
Remove caddy dependency

### ISSUE THREAD

**Issue by maxux** [threefoldtech/0-hub#16]
Caddy was there at the very first version when it was a simple directory listing protected by itsyou.online, since this project changed a lot and Caddy is a hard dependency adding more complexity than features.

It should now be removed and Flask should handle everything.

**Comment by maxux** [comment]
Required for #18

**Comment by maxux** [comment]
The current https://playground.hub.grid.tf/ website runs using `caddyless` branch, which works without caddy. This website should be tested to see if it's stable and usable.

**Comment by BolaNasr** [comment]
now : it works fine at  https://playground.hub.grid.tf/
