### ISSUE TITLE
Allow hub to works without authenfication for local usage

### ISSUE THREAD

**Issue by maxux** [threefoldtech/0-hub#17]
When deploying a hub locally for testing or personal usage, using authenfication with itsyou.online can be boring and not useful. A running mode without authentication would be important and simplify deploying a hub locally.

**Comment by maxux** [comment]
Required for #18

**Comment by maxux** [comment]
Branch https://github.com/threefoldtech/0-hub/tree/iyoless can works without authentication and have a really improved documentation about how config file works: https://github.com/threefoldtech/0-hub/blob/iyoless/python/config.py.sample

**Comment by BolaNasr** [comment]
it works good :+1:
