### ISSUE TITLE
Migrate from IYO to 3bot connect for authentication

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-hub#26]
- [x] implement 3bot connect on the hub web UI
- [ ] research how we can use 3bot connect for API authentication
- [ ] update all the tools around the hub to support 3bot connect (zflist, ....)

**Comment by maxux** [comment]
Threebot connect doesn't support something we can use for API authentication like we want. They are cooking something allowing this, but it's not ready yet. I close this issue and open a new one dedicated to API authentication.
