### ISSUE TITLE
wrong permission on / when doing docker conversion

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-hub#27]
I seems that when converting a docker image into an flist, the permission of the root (/) directory is set to `rwx------`. I think this is a mistake root directory should be traversalable for everyone so a more logical permission would be `rwx--x--x`.

I've had some flist that were not behaving properly because of this. After a `chmod 755 /` things went back to working ok.

Can we change the hub or zflist I don't know which one to use the proper permission ?

**Comment by maxux** [comment]
I can confirm it's a 0-flist (zflist / libflist) issue. Not a hub related issue or 0-fs issue.

**Comment by maxux** [comment]
Correction, this is actually maybe a hub issue. Hub still use old version of zflist which doesn't contains all latest fixes. I update flist module and zflist on playground.

**Comment by maxux** [comment]
Potential fix deployed on playground

**Comment by maxux** [comment]
Everything is live in production.
