### ISSUE TITLE
Couldn't deploy a vm or container from a merged flist

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/0-hub#34]
### 1- https://hub.grid.tf/qa_tft_1/ens4.flist
this flist contains only one file.

![image](https://user-images.githubusercontent.com/41957921/74825684-00bb9980-5313-11ea-8fb3-03dfd8120fd1.png)

### 3- Check that flist has been created.
![image](https://user-images.githubusercontent.com/41957921/74825863-4d9f7000-5313-11ea-883f-a47ef8105ef2.png)
![image](https://user-images.githubusercontent.com/41957921/74825957-6f98f280-5313-11ea-9739-d8394bf42152.png)

### 4-Try to create a vm or container using this flist.
I couldn't create a vm from the merged flist, however I could create a vm from https://hub.grid.tf/tf-bootable/ubuntu:18.04.flist and it was only one file has been changed.

![image](https://user-images.githubusercontent.com/41957921/74826947-28abfc80-5315-11ea-9185-925f68bca5d4.png)

### 5-Check with other flists
1- https://hub.grid.tf/tf-bootable/ubuntu:18.04.flist
2- https://hub.grid.tf/tf-autobuilder/threefoldtech-jumpscaleX_core-development.flist

![image](https://user-images.githubusercontent.com/41957921/74827734-94429980-5316-11ea-9c0c-4d694659c1f6.png)

![image](https://user-images.githubusercontent.com/41957921/74827439-226a5000-5316-11ea-81d3-ed043e1969b2.png)

#### This time it raises an error and couldn't deploy.
![image](https://user-images.githubusercontent.com/41957921/74828466-d5877900-5317-11ea-97c2-df6feeb68190.png)

**Comment by maxux** [comment]
I just checked content of https://hub.grid.tf/qa_tft_1/ubuntu_merge.flist.md and it looks like all directoriss on /etc where replaced by the unique directory /etc/netplan. This obviously break the system. The issue is in https://github.com/threefoldtech/0-flist/ side. I'll take a look.

**Comment by maxux** [comment]
Can you try again ?

**Comment by AhmedHanafy725** [comment]
I tried to merge the same flists again, and it works fine.
Thank you
