### ISSUE TITLE
entry point for an flist missing in hub

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/0-hub#38]
When an flist creator generates an flist and publishes it on the hub, there might be usage parameters needed such as an entry point. 
No possibility for the moment to add this entry point as a parameter or in an instruction manual in hub.grid.tf

Add a simple free text field to add this info ?

**Comment by maxux** [comment]
Thanks, here are multiple things regarding this issue.

First, I agree about the info/readme on the hub, we need to add something quickly. People probably use the hub uploader for most of their build, they don't do home made flist. I'm thinking about a text/markdown readme present on the root directory of the archive uploaded and this file would be used as readme on the hub to describe contents.

This is IMO doable quickly to get something to show. Would that be good for now ?

Second, flist itself support few metadata (entrypoing, environment variable, port mapping, mount volumes, readme, storage-url, ...). All of theses settings should be used to setup container settings. Right now, when a container start on Zero-OS, only the `/.startup.toml` file is used, which describe some of theses parameters.

@zaibon suggested to get a working workflow working like `Dockerfile` which would build, set parameters and upload flist automatically. This would come later.

**Comment by gmachtel** [comment]
Had feedback from users, they agree a readme box is a nice solution.

**Comment by zaibon** [comment]
@maxux Let's add a section about flist in the sdk manual where we document all feature and how to use the new readme feature.

**Comment by maxux** [comment]
https://github.com/threefoldfoundation/info_tfgridsdk/pull/115

**Comment by maxux** [comment]
Moving to production hub
