### ISSUE TITLE
Internal server error when converting a docker image

### ISSUE THREAD

**Issue by OmarElawady** [threefoldtech/0-hub#43]
When I convert the image `omarelawady/discourse_all_in_one`, the conversion takes some time then a page with internal server error is shown. After that an image with this name appears in my profile with the files in it but when I try to deploy it on zos core x doesn't initalize.
![image](https://user-images.githubusercontent.com/13040543/89797484-47a08400-db2b-11ea-8d54-39087511212d.png)

**Comment by OmarElawady** [comment]
I tried to deploy it again later and it worked normally with core x initialized. So now it's just the internal server error part.

**Comment by maxux** [comment]
It’s probably a timeout behind not handled, I’ll check it out

**Comment by zaibon** [comment]
I tested the faulty docker image again: omarelawady/discourse_all_in_one and here is the result:
![2020-08-24_1520x999_scrot](https://user-images.githubusercontent.com/303164/91018138-80426200-e5ef-11ea-8ef0-ef3cc9f6211b.png)

@maxux make sure you use this image for your tests please.

**Comment by maxux** [comment]
I did it. It probably caddy configuration now. Will check.

**Comment by maxux** [comment]
It was internal docker client timeout, cleaning up the image took more than 60 seconds.
Timeout was extended and progression were a lot improved. No more issue with this image on playground so far :)
