### ISSUE TITLE
flist contents empty  after convert docker image to flist

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/0-hub#48]
- i have installed 0-hub using deploy.sh script
- I have to convert docker image threefolddev/gitea_all_in_one is converted successfully without error as below but has no contents 
![image](https://user-images.githubusercontent.com/21987477/98797950-f51a8080-2415-11eb-9b0b-6ae896ee085e.png)

![image](https://user-images.githubusercontent.com/21987477/98798122-2abf6980-2416-11eb-9f5c-fe6a0d57bafa.png)

- no error in logs
- code version 
```
root@hub:/opt# cd 0-flist/
root@hub:/opt/0-flist# git log -1
commit fe9445c1245e8a7651ebbe2492bbc2f660dc189c (HEAD -> development-v2, tag: v2.0.0-rc1, origin/development-v2)
Merge: 67b9c2f 47ded86
Author: Maxime Daniel <maxux.unix@gmail.com>
Date:   Fri Aug 21 17:40:24 2020 +0200

```

**Comment by maxux** [comment]
This is probably your environment not configured correctly, not related to 0-hub code.
