### ISSUE TITLE
Login with threefold connect not working

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/0-hub#54]
## Description
Logging with threefold connect not working after the last update for threefold connect (But it is working in other things), The emoji appears and is received but can't choose it.

## Steps to reproduce
1. Login using a threefold connect
2. Click on the matching emoji
3. Nothing happen, still not reflected until it timeout and failed to login.

**Comment by maxux** [comment]
Fixed by https://github.com/threefoldtech/0-hub/commit/7d90d023f500ff647b13be2f597923ae96842f59 in production already.

**Comment by MElborolossy** [comment]
Fixed
