### ISSUE TITLE
upload returns an error

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/0-hub#66]
after trying to follow the steps of building an ubuntu vm flist, i tried to upload it to the hub, and the hub returned an http 502 error
![Screenshot from 2023-07-02 12-11-17](https://github.com/threefoldtech/0-hub/assets/26723944/4f7c9ab5-656d-4753-9052-cc0352011484)

the file is around 315MB.
i also tried to upload a small random tar file, and it was successful

**Comment by maxux** [comment]
It's not the first time I see someone reporting this. Will investigate.

**Comment by xmonader** [comment]
I moved it into in progress, but need to set a milestone (the upcoming release version of 0-hub) for it @maxux

**Comment by maxux** [comment]
Problem is, I don't know how to reproduce :/
