### ISSUE TITLE
docker converter is not working properly 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/0-hub#68]
i keep getting this error when trying to convert a docker image from the hub converter
![image](https://github.com/threefoldtech/0-hub/assets/32527347/a8177749-beec-4c12-aba0-ea9f639b8e7b)

it is not only for this image but fails with any other image. also it do work sometimes but most of the time fails

**Comment by maxux** [comment]
I checked hub logs, I don't see any error reason. I'll try to investigate. I see the conversion worked fined later ?

**Comment by Omarabdul3ziz** [comment]
yes it eventually works after multiple retries

**Comment by maxux** [comment]
Okay, we don't know yet exactly what happens but I could identify the problem. This is not hub code related but container and runtime issue. I'll open an issue with operation team to try to identify the problem, will keep this issue updated.

**Comment by maxux** [comment]
We updated some system configuration and DNS settings. Things should works more smoothly now :)
